export const FETCH_ALL_RECIPES = "FETCH_ALL_RECIPES";

export const ADD_NEW_INGREDIENT = "ADD_NEW_INGREDIENT";
export const ADD_NEW_DIRECTION = "ADD_NEW_DIRECTION";
export const ADD_NEW_NAME = "ADD_NEW_NAME";
export const POST_AND_RESET = "POST_AND_RESET";

export const GET_FULL_RECIPE = "GET_FULL_RECIPE";
export const DELETE_INGREDIENT_FROM_RECIPE = "DELETE_INGREDIENT_FROM_RECIPE";
export const DELETE_DIRECTION_FROM_RECIPE = "DELETE_DIRECTION_FROM_RECIPE";
export const ADD_INGREDIENT_TO_RECIPE = "ADD_INGREDIENT_TO_RECIPE";
export const ADD_DIRECTION_TO_RECIPE = "ADD_DIRECTION_TO_RECIPE";
